; SUBROUTINEs Test - DURATION: 265ns @ Clk = 1ns
; The following asm code focuses on context switches between subroutines subsequently
; called and returned, in order to test the window switch functionality of the Register
; File and its interface towards the Stack memory. Also, the correctness of the stalls
; generated by SPILL and FILL operations is being tested here, as well as unconditional
; jumps and Register Management Logic functionalities.

		;globals definition
		addi r1, r0, #10
		addi r3, r0, #30
		addi r5, r0, #50
		add r7, r5, r1		;forwarding EX/MEM.ALUOut to ALUIn_A + RF forwarding RdOut <= WrIn
		add r7, r7, r1		;forwarding EX/MEM.ALUOut to ALUIn_A
		addi r8, r0, #16535
		addi r18, r0, #16535
		jal subr1			;anticipation of JUMP mgmt + RF CALL
		nop
		j end
;subroutine 1
subr1:
		;in
		addi r8, r0, #8
		addi r9, r0, #9
		addi r10, r0, #10
		addi r11, r0, #11
		addi r12, r0, #12
		addi r13, r0, #13
		addi r14, r0, #14
		addi r15, r0, #15
		;locals
		addi r16, r0, #16
		addi r17, r0, #17
		addi r18, r0, #18
		addi r19, r0, #19
		addi r20, r0, #20
		addi r21, r0, #21
		addi r22, r0, #22
		;out
		addi r24, r0, #24
		addi r25, r0, #25
		addi r26, r0, #26
		addi r27, r0, #27
		addi r28, r0, #28
		addi r29, r0, #29
		addi r30, r0, #30
		addi r31, r0, #31
		jal subr2
		jr r23
		nop					;delay slot of Jump Register
		;subroutine 2
subr2:
		;locals
		addi r16, r0, #32
		addi r17, r0, #33
		addi r18, r0, #34
		addi r19, r0, #35
		addi r20, r0, #36
		addi r21, r0, #37
		addi r22, r0, #38
		;out      
		addi r24, r0, #40
		addi r25, r0, #41
		addi r26, r0, #42
		addi r27, r0, #43
		addi r28, r0, #44
		addi r29, r0, #45
		addi r30, r0, #46
		addi r31, r0, #47
		jal subr3
		jr r23
		nop					;delay slot of Jump Register
;subroutine 3
subr3:
		;locals
		addi r16, r0, #48
		addi r17, r0, #49
		addi r18, r0, #50
		addi r19, r0, #51
		addi r20, r0, #52
		addi r21, r0, #53
		addi r22, r0, #54
		;out      
		addi r24, r0, #56
		addi r25, r0, #57
		addi r26, r0, #58
		addi r27, r0, #59
		addi r28, r0, #60
		addi r29, r0, #61
		addi r30, r0, #62
		addi r31, r0, #63
		jal subr4
		jr r23
		nop					;delay slot of Jump Register
;subroutine 4
subr4:
		;locals
		addi r16, r0, #64
		addi r17, r0, #65
		addi r18, r0, #66
		addi r19, r0, #67
		addi r20, r0, #68
		addi r21, r0, #69
		addi r22, r0, #70
		;out      
		addi r24, r0, #72
		addi r25, r0, #73
		addi r26, r0, #74
		addi r27, r0, #75
		addi r28, r0, #76
		addi r29, r0, #77
		addi r30, r0, #78
		addi r31, r0, #79
		jal subr5
		jr r23
		nop					;delay slot of Jump Register
;subroutine 5
subr5:
		;locals
		addi r16, r0, #80
		addi r17, r0, #81
		addi r18, r0, #82
		addi r19, r0, #83
		addi r20, r0, #84
		addi r21, r0, #85
		addi r22, r0, #86
		;out      
		addi r24, r0, #88
		addi r25, r0, #89
		addi r26, r0, #90
		addi r27, r0, #91
		addi r28, r0, #92
		addi r29, r0, #93
		addi r30, r0, #94
		addi r31, r0, #95
		jal subr6
		jr r23
		nop					;delay slot of Jump Register
;subroutine 6
subr6:
		;locals
		addi r16, r0, #96
		addi r17, r0, #97
		addi r18, r0, #98
		addi r19, r0, #99
		addi r20, r0, #100
		addi r21, r0, #101
		addi r22, r0, #102
		;out      
		addi r24, r0, #104
		addi r25, r0, #105
		addi r26, r0, #106
		addi r27, r0, #107
		addi r28, r0, #108
		addi r29, r0, #109
		addi r30, r0, #110
		addi r31, r0, #111
		jal subr7			;this CALL needs a SPILL: IN+LOCALS of Wind#0 are spilled = 4 cc of stalls
		jr r23
		nop					;delay slot of Jump Register
;subroutine 7
subr7:
		;locals
		addi r16, r0, #112
		addi r17, r0, #113
		addi r18, r0, #114
		addi r19, r0, #115
		addi r20, r0, #116
		addi r21, r0, #117
		addi r22, r0, #118
		;out      
		addi r24, r0, #120
		addi r25, r0, #121
		addi r26, r0, #122
		addi r27, r0, #123
		addi r28, r0, #124
		addi r29, r0, #125
		addi r30, r0, #126
		addi r31, r0, #127
		jal subr8			;this CALL needs a SPILL: IN+LOCALS of Wind#1 are spilled = 4 cc of stalls
		jr r23
		nop					;delay slot of Jump Register
;subroutine 8
subr8:
		;locals
		addi r16, r0, #128
		addi r17, r0, #129
		addi r18, r0, #130
		addi r19, r0, #131
		addi r20, r0, #132
		addi r21, r0, #133
		addi r22, r0, #134
		;out      
		addi r24, r0, #136
		addi r25, r0, #137
		addi r26, r0, #138
		addi r27, r0, #139
		addi r28, r0, #140
		addi r29, r0, #141
		addi r30, r0, #142
		addi r31, r0, #143
		jal subr9			;this CALL needs a SPILL: IN+LOCALS of Wind#2 are spilled = 4 cc of stalls
		jr r23
		nop					;delay slot of Jump Register
;subroutine 9
subr9:
		;locals
		addi r16, r0, #144
		addi r17, r0, #145
		addi r18, r0, #146
		addi r19, r0, #147
		addi r20, r0, #148
		addi r21, r0, #149
		addi r22, r0, #150
		;out      
		addi r24, r0, #152
		addi r25, r0, #153
		addi r26, r0, #154
		addi r27, r0, #155
		addi r28, r0, #156
		addi r29, r0, #157
		addi r30, r0, #158
		addi r31, r0, #159
		jal subr10			;this CALL needs a SPILL: IN+LOCALS of Wind#3 are spilled = 4 cc of stalls
		jr r23
		nop					;delay slot of Jump Register
;subroutine 10
subr10:
		;locals
		addi r16, r0, #160
		addi r17, r0, #161
		addi r18, r0, #162
		addi r19, r0, #163
		addi r20, r0, #164
		addi r21, r0, #165
		addi r22, r0, #166
		;out      
		addi r24, r0, #168
		addi r25, r0, #169
		addi r26, r0, #170
		addi r27, r0, #171
		addi r28, r0, #172
		addi r29, r0, #173
		addi r30, r0, #174
		addi r31, r0, #175
		jal subr11			;this CALL needs a SPILL: IN+LOCALS of Wind#4 are spilled = 4 cc of stalls
		jr r23
		nop					;delay slot of Jump Register
;subroutine 11
subr11:
		;locals
		addi r16, r0, #176
		addi r17, r0, #177
		addi r18, r0, #178
		addi r19, r0, #179
		addi r20, r0, #180
		addi r21, r0, #181
		addi r22, r0, #182
		;out      
		addi r24, r0, #184
		addi r25, r0, #185
		addi r26, r0, #186
		addi r27, r0, #187
		addi r28, r0, #188
		addi r29, r0, #189
		addi r30, r0, #190
		addi r31, r0, #191
		jr r23
		nop					;delay slot of Jump Register

;end of the program
end:
		j end